[project]
name = "stt-realtime-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elevenlabs>=1.9.0",
    "numpy>=2.1.2",
    "python-dotenv>=1.0.1",
    "sounddevice>=0.5.0",
    "websockets>=13.1",
]
